name: Calculator CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile calculator
        run: g++ calculator.cpp mathfuncs.cpp -o calculator

      - name: Run calculator
        run: ./calculator

      - name: Compile tests
        run: g++ test_mathfuncs.cpp mathfuncs.cpp -o test_mathfuncs

      - name: Run tests
        run: ./test_mathfuncs
